version: "3.7"
services:
    packages:
      build:
        context: .
        dockerfile: docker/packages.Dockerfile
      volumes:
        - .:/var/base
    test:
      build:
        context: .
        dockerfile: docker/test.Dockerfile
      volumes:
        - .:/var/base
      depends_on:
        - packages
    transpile:
      build:
        context: .
        dockerfile: docker/transpile.Dockerfile
      volumes:
        - .:/var/base
      depends_on:
        - packages
